---
- hosts: jenkins
  become: yes
  roles:
    - geerlingguy.jenkins
    - geerlingguy.git
    - geerlingguy.repo-epel
    - sshkeys

  post_tasks:
    - name: Install ansible
      yum:
        name: ansible
        state: present

- hosts: artifactory
  become: yes
  roles:
    - jenscobie.artifactory

- hosts: service-api
  become: yes
  roles:
    - sshkeys

- hosts: database
  become: yes
  roles:
    - postgresql
